# Generated by Django 2.2 on 2020-06-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not started'), ('InProgress', 'InProgress'), ('Done', 'Done')], default='Not started', max_length=20),
        ),
    ]
