# Generated by Django 2.2 on 2020-06-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200607_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.Task'),
        ),
    ]
