# Generated by Django 2.2 on 2020-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('choose-grade', '----'), ('grade1', 'g1'), ('grade2', 'g2'), ('grade3', 'g3')], max_length=10)),
            ],
        ),
    ]
