# Generated by Django 2.2 on 2020-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='grade',
            field=models.CharField(choices=[('choose-grade', '----'), ('grade1', 'grade1'), ('grade2', 'grade2'), ('grade3', 'grade3')], max_length=10),
        ),
    ]
